name: ci

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  github-runtime:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Env before
        run: |
          env|sort
      -
        name: Expose GitHub Runtime
        uses: ./
      -
        name: Env after
        run: |
          env|sort
